services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.16
    container_name: sonarr
    networks:
      - aar
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/lach/configs/sonarr:/config
      - /data:/data
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:6.0.4
    container_name: radarr
    networks:
      - aar
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/lach/configs/radarr:/config
      - /data:/data
    ports:
      - 7878:7878
    restart: unless-stopped


  kometa:
    image: kometateam/kometa:v2.3.0
    container_name: kometa
    network_mode: bridge
    environment:
      - PMM_CONFIG=${KOMETA_PMM_CONFIG}
      - KOMETA_TIME=${KOMETA_TIME}
      - PLEX_UID=${PLEX_UID}
      - PLEX_GID=${PLEX_GID}
      - KOMETA_RUN=${KOMETA_RUN}
      - TZ=${TZ}
    volumes:
      - /home/lach/configs/kometa:/config
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.3.0
    container_name: prowlarr
    networks:
      - aar
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/lach/configs/prowlarr2:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:version-5.1.4-r2
    container_name: qbittorrent
    networks:
      - aar
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${QBITTORRENT_WEBUI_PORT}
      - TORRENTING_PORT=${QBITTORRENT_TORRENTING_PORT}
    volumes:
      - /home/lach/configs/qBittorrent:/config
      - /data/torrents:/data/torrents:rw
    ports:
      - 8082:8082
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:4.5.5
    container_name: sabnzbd
    networks:
      - aar
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/lach/configs/SABnzbd:/config
      - /data/usenet:/data/usenet:rw
    ports:
      - 8084:8084
    restart: unless-stopped

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:7.5.2
    container_name: recyclarr
    user: 1000:1000
    networks:
      - aar
    volumes:
      - /home/lach/configs/recyclarr:/config
    environment:
      - TZ=${TZ}
    restart: unless-stopped

  beszel-agent:
    image: henrygd/beszel-agent:0.18.4-alpine
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/lach/configs/beszel-agent:/var/lib/beszel-agent
      - /data/.beszel:/extra-filesystems/sda1__Media:ro
    devices:
      - /dev/sda:/dev/sda
      - /dev/nvme0:/dev/nvme0
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    environment:
      LISTEN: ${BESZEL_LISTEN}
      KEY: ${BESZEL_KEY}
      TOKEN: ${BESZEL_TOKEN}
      HUB_URL: ${BESZEL_HUB_URL}

  plex:
    image: lscr.io/linuxserver/plex:1.43.0
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=${PLEX_VERSION}
    volumes:
      - /home/lach/configs/plex:/config
      - /data/media/tv:/tv
      - /data/media/movies:/movies
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:2026.2.0
    container_name: cloudflared
    networks:
      - aar
      - monitoring
    environment:
      - TZ=${TZ}
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TUNNEL_TOKEN}
    restart: unless-stopped

  flaresolverr:
    image: flaresolverr/flaresolverr:v3.4.6
    container_name: flaresolverr
    networks:
      - aar
    environment:
      - TZ=${TZ}
    ports:
      - 8191:8191
    restart: unless-stopped

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:2026.1.2
    container_name: homeassistant
    network_mode: host
    environment:
      - TZ=${TZ}
    volumes:
      - /home/lach/configs/homeassistant:/config
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:2.33.6
    container_name: portainer
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/lach/configs/portainer:/data
    ports:
      - 9000:9000
    restart: unless-stopped

  archisteamfarm:
    image: justarchi/archisteamfarm:6.3.1.6
    container_name: asf
    network_mode: bridge
    environment:
      - ASF_CRYPTKEY=${ASF_CRYPTKEY}
    volumes:
      - /home/lach/configs/asf:/app/config
      - /home/lach/configs/asf/logs:/app/logs
    ports:
      - 1242:1242
    restart: unless-stopped

  cleanuparr:
    image: ghcr.io/cleanuparr/cleanuparr:2.5.1
    container_name: cleanuparr
    networks:
      - aar
    environment:
      - PORT=${CLEANUPARR_PORT}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${CLEANUPARR_UMASK}
      - TZ=${TZ}
    volumes:
      - /home/lach/configs/cleanuparr:/config
    ports:
      - 11011:11011
    restart: unless-stopped

  pulsarr:
    image: lakker/pulsarr:0.12.2
    container_name: pulsarr
    networks:
      - aar
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - baseUrl=${PULSARR_BASE_URL}
      - port=${PULSARR_PORT}
      - logLevel=${PULSARR_LOG_LEVEL}
      - NODE_ARGS=${PULSARR_NODE_ARGS}
    volumes:
      - /home/lach/configs/pulsarr:/app/data
    ports:
      - 3003:3003
    restart: unless-stopped

networks:
  aar:
    external: true
    name: arr
  monitoring:
    external: true
    name: monitoring
