services:
  radarr:
    image: lscr.io/linuxserver/radarr:6.0.4.10291-ls294
    container_name: radarr
    networks:
      - aar
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/lach/configs/radarr:/config
      - /data:/data
    ports:
      - 7878:7878
    restart: unless-stopped


  kometa:
    image: kometateam/kometa:v2.3.0
    container_name: kometa
    network_mode: bridge
    environment:
      - PMM_CONFIG=${KOMETA_PMM_CONFIG}
      - KOMETA_TIME=${KOMETA_TIME}
      - PLEX_UID=${PLEX_UID}
      - PLEX_GID=${PLEX_GID}
      - KOMETA_RUN=${KOMETA_RUN}
      - TZ=${TZ}
    volumes:
      - /home/lach/configs/kometa:/config
    restart: unless-stopped

  beszel-agent:
    image: henrygd/beszel-agent:0.18.4-alpine
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/lach/configs/beszel-agent:/var/lib/beszel-agent
      - /data/.beszel:/extra-filesystems/sda1__Media:ro
    devices:
      - /dev/sda:/dev/sda
      - /dev/nvme0:/dev/nvme0
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    environment:
      LISTEN: ${BESZEL_LISTEN}
      KEY: ${BESZEL_KEY}
      TOKEN: ${BESZEL_TOKEN}
      HUB_URL: ${BESZEL_HUB_URL}

  plex:
    image: lscr.io/linuxserver/plex:1.43.0.10492-121068a07-ls295
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=${PLEX_VERSION}
    volumes:
      - /home/lach/configs/plex:/config
      - /data/media/tv:/tv
      - /data/media/movies:/movies
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:2026.2.0
    container_name: cloudflared
    networks:
      - aar
      - monitoring
    environment:
      - TZ=${TZ}
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TUNNEL_TOKEN}
    restart: unless-stopped

networks:
  aar:
    external: true
    name: arr
  monitoring:
    external: true
    name: monitoring
