version: '3.8'

services:
  radarr:
    image: lscr.io/linuxserver/radarr:6.0.4.10291-ls290
    container_name: radarr
    networks:
      - aar
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./configs/radarr:/config
      - /data:/data
    ports:
      - 7878:7878
    restart: unless-stopped

networks:
  aar:
    external: true
    name: arr
