services:
  traefik:
    image: traefik:v3.6
    container_name: traefik
    network_mode: host
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - /home/lach/configs/traefik:/etc/traefik
    restart: unless-stopped

  coredns:
    image: coredns/coredns:1.14.2
    container_name: coredns
    network_mode: host
    command: -conf /etc/coredns/Corefile
    volumes:
      - /home/lach/configs/coredns:/etc/coredns
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:2026.3.0
    container_name: cloudflared
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TUNNEL_TOKEN}
    restart: unless-stopped
    networks:
      - sour

  beszel-agent:
    image: henrygd/beszel-agent:0.18.4-alpine
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/lach/configs/beszel-agent:/var/lib/beszel-agent
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    environment:
      LISTEN: ${BESZEL_LISTEN}
      KEY: ${BESZEL_KEY}
      TOKEN: ${BESZEL_TOKEN}
      HUB_URL: ${BESZEL_HUB_URL}

  beszel:
    image: henrygd/beszel:0.18.4
    container_name: beszel
    ports:
      - 8090:8090
    volumes:
      - /home/lach/configs/beszel:/beszel_data
    restart: unless-stopped
    networks:
      - sour

  archisteamfarm:
    image: justarchi/archisteamfarm:6.3.3.3
    container_name: asf
    network_mode: bridge
    environment:
      - ASF_CRYPTKEY=${ASF_CRYPTKEY}
    volumes:
      - /home/lach/configs/asf:/app/config
      - /home/lach/configs/asf/logs:/app/logs
    ports:
      - 1242:1242
    restart: unless-stopped

  backup:
    image: lachlan443/backblaze-backup:1.2.0
    container_name: backup
    environment:
      - TZ=${TZ}
    volumes:
      - /home/lach/configs/backup:/config
      - /home/lach/backups:/backups
      - /home/lach:/source:ro
    restart: unless-stopped

networks:
  sour:
    name: sour
