services:
  nginx:
    image: nginx:1.27.4
    container_name: nginx
    ports:
      - 80:80
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:2026.2.0
    container_name: cloudflared
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TUNNEL_TOKEN}
    restart: unless-stopped
