name: llm

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:2026.6.3
    container_name: homeassistant
    networks:
      - llm
      - media
      - proxy
    env_file:
      - /home/lach/configs/homeassistant/.env
    volumes:
      - /home/lach/configs/homeassistant:/config
    restart: unless-stopped

networks:
  media:
    name: media
    external: true
  proxy:
    name: proxy
    external: true
