services:
  trilium:
    image: triliumnext/trilium:v0.103.0
    container_name: trilium
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
    volumes:
      - /home/lach/configs/trilium:/home/node/trilium-data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8087:8080
    restart: unless-stopped
