name: Docker Deploy

on:
  push:
    branches: [main]
    paths:
      - 'docker/compose.yaml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Set git safe directory
        run: git config --global --add safe.directory /home/lach/iac

      - name: Pull latest changes
        run: git -C /home/lach/iac pull

      - name: Pull updated images
        working-directory: /home/lach/iac/docker
        run: docker compose pull

      - name: Deploy
        working-directory: /home/lach/iac/docker
        run: docker compose up -d

      - name: Clean up old images
        run: docker image prune -f
